### ISSUE TITLE
Brs doesn't support the native tr() function

### ISSUE THREAD

**Issue by vbuchii** [sjbarag/brs#496]
For strings assigned using BrightScript in a <script> element, you can use the **tr()** function to localize a string:
https://developer.roku.com/docs/developer-program/core-concepts/localization.md

The test is interrupted with this error: `source/utilities/Localization.brs(3,42-43): 'tr' is not a function and cannot be called.`

**Comment by adheus** [comment]
If it helps you or anyone that might come into this issue, I'm using the following mock for now:

```
_brs_.mockFunction("tr", function(value)
        ?"[MOCK][TR]:";value
        return value
    end function)
```

**Comment by vbuchii** [comment]
Hi @lkipke 
Thanks for fixing it. Unfortunately, there is still an issue with `tr()` function. Now we do not see the previous warning but it returns `source` instead of `translation`.

Ex:
```
tr("Hello") ' returns "Hello"

<message> 
    <source>Hello</source> 
    <translation>Bonjour</translation> 
</message> 
```

**Comment by strattonbrazil** [comment]
Hi @vbuchii , by design the *tr* function returns the source string if the mapping for the given locale isn't provided. From Roku's [tr docs](https://developer.roku.com/docs/references/brightscript/language/global-utility-functions.md#trsource-as-string-as-string):

> If the translations.xml file exists for the current locale, and contains the source string with a translated string, the function returns the translated string. Otherwise, the function returns the original source string.

I'm guessing that's what's happening in your case. Because setting the locale isn't exposed in the Roku API, [a work-around utility was added to set it](https://github.com/sjbarag/brs/pull/578/files#diff-fbdea02b9b72e783f3989f178fd3afb9244b0af4cbcb89b5999b3276f528091fR2-R3). 

```
    _brs_.process.setLocale("en_US")
    print tr("Hello") ' => Bonjour
```

Sidenote: the example in the end-to-end test above is hilarious. 

Are you setting the locale and still not seeing the correct translation?

**Comment by vbuchii** [comment]
Hi @strattonbrazil
Thanks for your help, `getCurrentLocale()` function shows that locale is already "en_US" without additional setting. 
`translations.xml` contains a source that I'm trying to use and an additional setting ` _brs_.process.setLocale("en_US")` doesn't really help.
